### PR TITLE
Fixed Genre Page readability

### PR DESCRIPTION
**Pull request by roundband5**
Aligned song index number with the song name.
Genre Description now auto resizes depending on the window size.
Made the Genre name smaller.
Genre images are now grabbed from the assets folder

image
image

### CODE REVIEW

**Review by leonzh2k — CHANGES_REQUESTED** [review]
I think the song number is a bit too close to the song name. Should space it out like the Song page and the Search Page do.

**Review by lchua2314 — CHANGES_REQUESTED** [review]
Fix what leonzh2k wrote then it looks good. However, I would still like the page to look like Napster's page or close to the styling to what our home page and song page page looks like. You can do that in another pull request tho.

**Comment by roundband5** [comment]
Fixed spacing between song title and song index
image

**Review by lchua2314 — APPROVED** [review]
Looks good

**Comment by lchua2314** [comment]
Actually, I don't see the commit that adds the changes you made. Can you double check to make sure you pushed new changes on to GitHub?

**Comment by roundband5** [comment]
> Actually, I don't see the commit that adds the changes you made. Can you double check to make sure you pushed new changes on to GitHub?

You're right. I forgot to push the commits... It should be up now

**Review by leonzh2k — APPROVED** [review]
All good now. Merging.

**Pull request merged**
